name: Emscripten-CMake

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    #    steps:
    #      - uses: mymindstorm/setup-emsdk@v11
    #
    #      - name: Verify
    #        run: emcc -v

    steps:
      - uses: lovasoa/setup-emscripten@master
        with:
          emscripten-version: '1.38.47'
      - run: emcc --version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          emcmake cmake .
          emmake make

#      - name: Upload to branch
#        uses: actions/upload-artifact@v2
#        with:
#          name: emscripten-cmake
#          path: build-commandline
