name: Emscripten-Publish

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, but don't cancel an in-progress production deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  EMSDK_VERSION: 3.1.37

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v16
        with:
          version: ${{ env.EMSDK_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Verify
        run: emcc -v

      - name: Build
        run: |
          emcmake cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./web

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
